version: '3'
services:
  web:
    build: 
      context: ./bin_auto_admin/
      dockerfile: Dockerfile
    environment:
      DB_NAME    : 'bin_auto_tables'
      DB_USER    : 'postgres'
      DB_PASSWORD: 'superpassword3000'
      DB_HOST    : db
      DB_PORT    : 5432
    ports:
      - 8000:8000
    volumes:
      - ./bin_auto_admin:/app
    depends_on:
      - db
    # restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB      : 'bin_auto_tables'
      POSTGRES_USER    : 'postgres'
      POSTGRES_PASSWORD: 'superpassword3000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # restart: always

volumes:
  pgdata:
    external: true