# Generated by Django 4.2.6 on 2023-10-10 12:52

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='car_model',
            field=models.TextField(default=builtins.any),
            preserve_default=False,
        ),
    ]
